var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var g=a[d];g in c||(c[g]={});c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var d=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var g=d.length,b=a.length;c=Math.max(0,Math.min(c|0,d.length));for(var e=0;e<b&&c<g;)if(d[c++]!=a[e++])return!1;return e>=b}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;
$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return c})}},"es6","es3");
(function(a,b){var c=function(a,g,b){var d;return function(){var e=this,c=arguments;d?clearTimeout(d):b&&a.apply(e,c);d=setTimeout(function(){b||a.apply(e,c);d=null},g||100)}};jQuery.fn[b]=function(a){return a?this.bind("resize",c(a)):this.trigger(b)}})(jQuery,"smartresize");$(function(){"function"===typeof window.resize&&($(window).smartresize(function(){window.resize()}),$(window).load(function(){window.resize()}))});
function getWindowSize(){var a=0,b=0;if(window.innerHeight)a=window.innerHeight,b=window.innerWidth;else{var c=window.document.body;c.parentNode.clientHeight?(a=c.parentNode.clientHeight,b=c.parentNode.clientWidth):c&&c.clientHeight&&(a=c.clientHeight,b=c.clientWidth)}return{h:a,w:b}}function resizeElementHeight(a,b){a.style.height=getWindowSize().h-b+"px"}function resizeElementWidth(a,b){a.style.width=getWindowSize().w-b+"px"}function gotoIndex(){top.location.pathname="/"}
function getAppRootPath(){var a=top.location;return a.protocol+"//"+a.host+"/"}function getLocationParamByName(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(a[1].replace(/\+/g," "))}
function getBrowserName(){var a=!!document.documentMode;return a?"ie":(a="undefined"!==typeof window.InstallTrigger)?"firefox":(a=!!window.chrome&&!!window.chrome.webstore)?"chrome":(a=!!window.StyleMedia)?"edge":(a=!!window.opr&&!!window.opr.addons||!!window.opera||0<=navigator.userAgent.indexOf(" OPR/"))?"opera":(a=/constructor/i.test(window.HTMLElement)||"[object SafariRemoteNotification]"===(!window.safari||window.safari.pushNotification).toString())?"sofari":"Unknow browser"}
function myuploadfile(a,b,c,d){myajax(a,b,d,{cache:!1,contentType:!1,processData:!1,progressHandler:c})}var myajax_default_config={type:"POST",dataType:"json",timeout:3E4,contentType:"application/x-www-form-urlencoded;charset=UTF-8",async:!0,befohttp_statusend:null,global:!0,cache:!1,processData:!0,errorHandler:showError,respHandler:respHandler};
function myajax(a,b,c,d){d=$.extend(myajax_default_config,d||{});$.ajax({url:a,type:d.type,data:b,cache:d.cache,dataType:d.dataType,timeout:d.timeout,contentType:d.contentType,async:d.async,befohttp_statusend:d.befohttp_statusend,global:d.global,processData:d.processData,xhr:function(){var a=$.ajaxSettings.xhr();a.upload&&"function"===typeof d.progressHandler&&a.upload.addEventListener("progress",d.progressHandler,!1);return a},complete:function(b,f){(f=getReqBadStatus(b,f))?(f.url=a,f.level="fatal",
d.errorHandler(f),b=null):b=d.respHandler(b.responseText,d.errorHandler);c&&("function"===typeof c?c(b):c.success&&null!==b&&c.success(b))}})}function showError(a){window.top.showTopDialog?(a.level||(a.level="error"),a.title="<span title='"+a.url+"'>"+a.title+"</span>",window.top.showTopDialog(a)):alert("url="+a.url+", title="+a.title+"\nmessage="+a.message)}
var http_status={100:"\u5ba2\u6237\u5fc5\u987b\u7ee7\u7eed\u53d1\u51fa\u8bf7\u6c42",101:"\u5ba2\u6237\u8981\u6c42\u670d\u52a1\u5668\u6839\u636e\u8bf7\u6c42\u8f6c\u6362HTTP\u534f\u8bae\u7248\u672c",200:"\u4ea4\u6613\u6210\u529f",201:"\u63d0\u793a\u77e5\u9053\u65b0\u6587\u4ef6\u7684URL",202:"\u63a5\u53d7\u548c\u5904\u7406\u3001\u4f46\u5904\u7406\u672a\u5b8c\u6210",203:"\u8fd4\u56de\u4fe1\u606f\u4e0d\u786e\u5b9a\u6216\u4e0d\u5b8c\u6574",204:"\u8bf7\u6c42\u6536\u5230\uff0c\u4f46\u8fd4\u56de\u4fe1\u606f\u4e3a\u7a7a",
205:"\u670d\u52a1\u5668\u5b8c\u6210\u4e86\u8bf7\u6c42\uff0c\u7528\u6237\u4ee3\u7406\u5fc5\u987b\u590d\u4f4d\u5f53\u524d\u5df2\u7ecf\u6d4f\u89c8\u8fc7\u7684\u6587\u4ef6",206:"\u670d\u52a1\u5668\u5df2\u7ecf\u5b8c\u6210\u4e86\u90e8\u5206\u7528\u6237\u7684GET\u8bf7\u6c42",300:"\u8bf7\u6c42\u7684\u8d44\u6e90\u53ef\u5728\u591a\u5904\u5f97\u5230",301:"\u5220\u9664\u8bf7\u6c42\u6570\u636e",302:"\u5728\u5176\u4ed6\u5730\u5740\u53d1\u73b0\u4e86\u8bf7\u6c42\u6570\u636e",303:"\u5efa\u8bae\u5ba2\u6237\u8bbf\u95ee\u5176\u4ed6URL\u6216\u8bbf\u95ee\u65b9\u5f0f",
304:"\u5ba2\u6237\u7aef\u5df2\u7ecf\u6267\u884c\u4e86GET\uff0c\u4f46\u6587\u4ef6\u672a\u53d8\u5316",305:"\u8bf7\u6c42\u7684\u8d44\u6e90\u5fc5\u987b\u4ece\u670d\u52a1\u5668\u6307\u5b9a\u7684\u5730\u5740\u5f97\u5230",306:"\u524d\u4e00\u7248\u672cHTTP\u4e2d\u4f7f\u7528\u7684\u4ee3\u7801\uff0c\u73b0\u884c\u7248\u672c\u4e2d\u4e0d\u518d\u4f7f\u7528",307:"\u7533\u660e\u8bf7\u6c42\u7684\u8d44\u6e90\u4e34\u65f6\u6027\u5220\u9664",400:"\u9519\u8bef\u8bf7\u6c42\uff0c\u5982\u8bed\u6cd5\u9519\u8bef",401:"\u8bf7\u6c42\u6388\u6743\u5931\u8d25",
402:"\u4fdd\u7559\u6709\u6548ChargeTo\u5934\u54cd\u5e94",403:"\u8bf7\u6c42\u4e0d\u5141\u8bb8",404:"\u6ca1\u6709\u53d1\u73b0\u6587\u4ef6\u3001\u67e5\u8be2\u6216URL",405:"\u7528\u6237\u5728Request-Line\u5b57\u6bb5\u5b9a\u4e49\u7684\u65b9\u6cd5\u4e0d\u5141\u8bb8",406:"\u6839\u636e\u7528\u6237\u53d1\u9001\u7684Accept\u62d6\uff0c\u8bf7\u6c42\u8d44\u6e90\u4e0d\u53ef\u8bbf\u95ee",407:"\u7c7b\u4f3c401\uff0c\u7528\u6237\u5fc5\u987b\u9996\u5148\u5728\u4ee3\u7406\u670d\u52a1\u5668\u4e0a\u5f97\u5230\u6388\u6743",
408:"\u5ba2\u6237\u7aef\u6ca1\u6709\u5728\u7528\u6237\u6307\u5b9a\u7684\u997f\u65f6\u95f4\u5185\u5b8c\u6210\u8bf7\u6c42",409:"\u5bf9\u5f53\u524d\u8d44\u6e90\u72b6\u6001\uff0c\u8bf7\u6c42\u4e0d\u80fd\u5b8c\u6210",410:"\u670d\u52a1\u5668\u4e0a\u4e0d\u518d\u6709\u6b64\u8d44\u6e90\u4e14\u65e0\u8fdb\u4e00\u6b65\u7684\u53c2\u8003\u5730\u5740",411:"\u670d\u52a1\u5668\u62d2\u7edd\u7528\u6237\u5b9a\u4e49\u7684Content-Length\u5c5e\u6027\u8bf7\u6c42",412:"\u4e00\u4e2a\u6216\u591a\u4e2a\u8bf7\u6c42\u5934\u5b57\u6bb5\u5728\u5f53\u524d\u8bf7\u6c42\u4e2d\u9519\u8bef",
413:"\u8bf7\u6c42\u7684\u8d44\u6e90\u5927\u4e8e\u670d\u52a1\u5668\u5141\u8bb8\u7684\u5927\u5c0f",414:"\u8bf7\u6c42\u7684\u8d44\u6e90URL\u957f\u4e8e\u670d\u52a1\u5668\u5141\u8bb8\u7684\u957f\u5ea6",415:"\u8bf7\u6c42\u8d44\u6e90\u4e0d\u652f\u6301\u8bf7\u6c42\u9879\u76ee\u683c\u5f0f",416:"\u8bf7\u6c42\u4e2d\u5305\u542bRange\u8bf7\u6c42\u5934\u5b57\u6bb5\uff0c\u5728\u5f53\u524d\u8bf7\u6c42\u8d44\u6e90\u8303\u56f4\u5185\u6ca1\u6709range\u6307\u793a\u503c\uff0c\u8bf7\u6c42\u4e5f\u4e0d\u5305\u542bIf-Range\u8bf7\u6c42\u5934\u5b57\u6bb5",
417:"\u670d\u52a1\u5668\u4e0d\u6ee1\u8db3\u8bf7\u6c42Expect\u5934\u5b57\u6bb5\u6307\u5b9a\u7684\u671f\u671b\u503c\uff0c\u5982\u679c\u662f\u4ee3\u7406\u670d\u52a1\u5668\uff0c\u53ef\u80fd\u662f\u4e0b\u4e00\u7ea7\u670d\u52a1\u5668\u4e0d\u80fd\u6ee1\u8db3\u8bf7\u6c42",500:"\u670d\u52a1\u5668\u4ea7\u751f\u5185\u90e8\u9519\u8bef",501:"\u670d\u52a1\u5668\u4e0d\u652f\u6301\u8bf7\u6c42\u7684\u51fd\u6570",502:"\u670d\u52a1\u5668\u6682\u65f6\u4e0d\u53ef\u7528\uff0c\u6709\u65f6\u662f\u4e3a\u4e86\u9632\u6b62\u53d1\u751f\u7cfb\u7edf\u8fc7\u8f7d",
503:"\u670d\u52a1\u5668\u8fc7\u8f7d\u6216\u6682\u505c\u7ef4\u4fee",504:"\u5173\u53e3\u8fc7\u8f7d\uff0c\u670d\u52a1\u5668\u4f7f\u7528\u53e6\u4e00\u4e2a\u5173\u53e3\u6216\u670d\u52a1\u6765\u54cd\u5e94\u7528\u6237\uff0c\u7b49\u5f85\u65f6\u95f4\u8bbe\u5b9a\u503c\u8f83\u957f",505:"\u670d\u52a1\u5668\u4e0d\u652f\u6301\u6216\u62d2\u7edd\u652f\u8bf7\u6c42\u5934\u4e2d\u6307\u5b9a\u7684HTTP\u7248\u672c"};
function getReqBadStatus(a,b){if(4===a.readyState)return 200===a.status?null:401===a.status?(gotoIndex(),null):403===a.status?{title:"\u8bf7\u6c42\u88ab\u62d2\u7edd",message:"\u6743\u9650\u4e0d\u8db3\uff0c\u8bf7\u6c42\u88ab\u62d2\u7edd"}:{title:"http\u72b6\u6001\u9519\u8bef",message:"Error:\n\tcode="+a.status+"\n\tmessage="+http_status[a.status]+" - "+b};switch(a.readyState+""){case "0":if("timeout"===b)return{title:"\u8bf7\u6c42\u8d85\u65f6",message:"\u7b49\u5f85\u670d\u52a1\u5668\u5904\u7406\u8d85\u65f6\uff08\u670d\u52a1\u5668\u5904\u7406\u65f6\u95f4\u8fc7\u957f\uff09\u3002"};
break;case "1":return{title:"\u72b6\u6001\u9519\u8bef",message:"Error:\n\tcode="+a.readyState+"\n\tmessage=\u7b49\u5f85\u670d\u52a1\u5668\u54cd\u5e94\u5931\u8d25\u3002\u53ef\u80fd\u670d\u52a1\u5668\u5173\u95ed\u6216\u7f51\u7edc\u4e0d\u7a33\u5b9a\u3002"};case "2":return{title:"\u72b6\u6001\u9519\u8bef",message:"Error:\n\tcode="+a.readyState+"\n\tmessage=\u63a5\u6536\u5230\u670d\u52a1\u5668\u6570\u636e\u540e\u53d1\u751f\u9519\u8bef\u3002"};case "3":return{title:"\u72b6\u6001\u9519\u8bef",message:"Error:\n\tcode="+
a.readyState+"\n\tmessage=\u89e3\u6790\u670d\u52a1\u5668\u6570\u636e\u65f6\u53d1\u751f\u9519\u8bef\u3002"}}return{title:"\u72b6\u6001\u9519\u8bef",message:"Error:\n\tcode="+a.readyState+"\n\tmessage="+a.statusText}}
function respHandler(a,b){if("string"===typeof a)try{a=JSON.parse(a)}catch(c){return b({title:"\u8fd4\u56de\u503c\u975ejson\u683c\u5f0f",message:"Text="+a}),null}if(!a)return null;if(0===a.RC)return null==a.ctx?"":a.ctx;switch(a.RC){case 2:(a=parseFormValidError(a.ctx))&&b({title:"\u8868\u5355\u6570\u636e\u6821\u9a8c\u9519\u8bef",message:a});break;default:b({title:"\u9519\u8bef",message:j2s(a.ctx)})}return null}
function parseFormValidError(a){if(!a||"object"!==typeof a)return" \u63d0\u793a"+(a?","+a:"<null>");var b="",c=!1;for(d in a){var d=a[d];var g=$("#"+d.field+"_err");g.length&&(g.html($.trim(d.error).length?d.error:"<img src='../images/plaint.png'>"),c=!0);b+=d.field+":"+d.error+"<br />"}return c?null:b}function isEmpty(a){if(null==a)return!0;if(0<a.length)return!1;if(0===a.length)return!0;for(var b in a)if(Object.prototype.hasOwnProperty.call(a,b))return!1;return!0}
function j2s(a){return isEmpty(a)?"":"object"===typeof a?JSON.stringify(a):a}function s2j(a){return a?"string"===typeof a?JSON.parse(a):a:null}function safe_j2s(a){if(isEmpty(a))return"";if("object"===typeof a){var b=[];return JSON.stringify(a,function(a,d){if("object"===typeof d&&null!==d){if(-1!==b.indexOf(d))return;b.push(d)}return d})}return a}var str2json=s2j,json2str=j2s;String.prototype.startsWith=function(a){return this.slice(0,a.length)===a};
String.prototype.endsWith=function(a){return""===a||this.slice(-a.length)===a};String.prototype.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};String.prototype.ltrim=function(){return this.replace(/(^\s*)/g,"")};String.prototype.rtrim=function(){return this.replace(/(\s*$)/g,"")};String.prototype.replaceAll=function(a,b,c){a=a.replace(/([.*+?^=!:${}()|\[\]\/\\])/g,"\\$1");return this.replace(new RegExp(a,c?"gi":"g"),b)};
function gen_uuid(a){var b=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};return(a?a+"-":"")+b()+b()+"-"+b()+"-"+b()+"-"+b()+"-"+b()+b()+b()}var app={};
$(function(){function a(a){var d,c=function(a){a=map.getView().calculateExtent(map.getSize());if(d)d=!1;else{var b=l.getProperties().getSelTypeNames();myajax("../wfs?Request=GetFeature",{typeNames:b.typeNames,subTypeNames:b.subTypeNames.join(","),bbox:a.join(",")},function(a){if(a){var b=l.getSource();d=!0;b.clear(!0);var g=[];$.each(a.charts,function(){var a=(new ol.format.WKT).readFeature(this.geometry_wkt);a.setId(this.id);a.setProperties(this.properties);a.setProperties({type:this.type});g.push(a)});
b.addFeatures(g);l.set("meta",a.meta)}})}},e=new ol.source.Vector({loader:c,useSpatialIndex:!1,format:new ol.format.GeoJSON,strategy:ol.loadingstrategy.bbox});e.setProperties({loader:c});var l=new ol.layer.Vector({source:e,style:b,name:"\u6d77\u56fe"+a.name,id:a.name,visible:!1,opacity:.8,ENC:!0});l.setProperties({typelist:a.typelist});return l}var b=function(a,b,c){var d=a.get("type"),g="blue";b="#00FFFF";c=0;a.get("highlight")&&(b=g="red",c=10);var f=a.getGeometry().getExtent(),k=map.getPixelFromCoordinate(ol.extent.getBottomLeft(f));
f=map.getPixelFromCoordinate(ol.extent.getTopRight(f));var m=f[0]-k[0],p=k[1]-f[1];k=function(b,c){return d.startsWith("AVCS Units ")&&(m<3*b||p<b)?null:new ol.style.Text({text:a.get("chartNumber"),fill:c?new ol.style.Fill({color:"#555"}):null,stroke:new ol.style.Stroke({color:g,width:1}),font:"normal normal "+b+"px Courier New"})};switch(d){case "AVCS Folio Transit":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:3}),fill:null,text:k(16,!1),zIndex:1+c});case "AVCS Folio Regional":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,
width:2}),fill:null,text:k(14,!1),zIndex:2+c});case "AVCS Folio Port":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:1}),fill:new ol.style.Fill({color:"rgba(100,100,100,0.2)"}),text:k(16,!0),zIndex:3+c});case "AVCS Units Overview":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:1}),fill:null,text:k(14,!0),zIndex:1+c});case "AVCS Units General":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:1}),fill:new ol.style.Fill({color:"rgba(100,100,100,0.2)"}),
text:k(14,!0),zIndex:2+c});case "AVCS Units Coastal":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:1}),fill:new ol.style.Fill({color:"rgba(100,100,100,0.2)"}),text:k(14,!0),zIndex:3+c});case "AVCS Units Approach":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:1}),fill:new ol.style.Fill({color:"rgba(100,100,100,0.2)"}),text:k(14,!0),zIndex:4+c});case "AVCS Units Harbour":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:1}),fill:new ol.style.Fill({color:"rgba(100,100,100,0.2)"}),
text:k(14,!0),zIndex:5+c});case "AVCS Units Berthing":return new ol.style.Style({stroke:new ol.style.Stroke({color:b,width:1}),fill:new ol.style.Fill({color:"rgba(100,100,100,0.2)"}),text:k(14,!0),zIndex:6+c})}};myajax("../wfs?Request=getTypeNames",null,function(b){b&&$.each(b,function(){var b=a(this);map.addLayer(b)})});var c=new ol.layer.Vector({id:"findENC",source:new ol.source.Vector,style:b,ENC:!0,zIndex:100});map.addLayer(c)});
function featureToTableElement(a){var b={id:a.getId(),chartType:a.get("type"),chartNumber:a.get("chartNumber"),chartTitle:a.get("chartTitle"),chartScale:"1 : "+a.get("chartScale"),chartPrices:a.get("prices")},c=a.get("subunits");c&&(a=c,c=[],$.each(a,function(){c.push(this.properties)}),b.subunits=c);return b}
(function(){function a(a,b){var d=b.color,c=b.image;a.get("readonly")&&(d="#c7840e",c="images/arrow-y2.png");var g=[new ol.style.Style({stroke:new ol.style.Stroke({color:d,width:b.width,lineCap:"butt"}),fill:new ol.style.Fill({color:"rgba(255, 255, 255, 0.5)"})})];a=a.getGeometry();a instanceof ol.geom.LineString&&a.forEachSegment(function(a,b){a=Math.atan2(b[1]-a[1],b[0]-a[0]);g.push(new ol.style.Style({geometry:new ol.geom.Point(b),image:new ol.style.Icon({src:c,anchor:[.65,.5],rotateWithView:!0,
rotation:-a})}))});return g}function b(a,b,f){a.set("tooltip",b);a.getGeometry().on("change",function(a){a=a.target;if(a instanceof ol.geom.Polygon){var b=map.getView().getProjection();b=a.clone().transform(b,"EPSG:4326").getLinearRing(0).getCoordinates();b=Math.abs(c.geodesicArea(b));b=1E4<b?Math.round(b/1E6*100)/100+" km<sup>2</sup>":Math.round(100*b)/100+" m<sup>2</sup>";var d=a.getInteriorPoint().getCoordinates()}else if(a instanceof ol.geom.LineString){d=a.getCoordinates();b=0;for(var g=map.getView().getProjection(),
e=0,f=d.length-1;e<f;++e){var q=ol.proj.transform(d[e],g,"EPSG:4326"),r=ol.proj.transform(d[e+1],g,"EPSG:4326");b+=c.haversineDistance(q,r)}b=100<b?Math.round(b/1E3*100)/100+" km":Math.round(100*b)/100+" m";d=a.getLastCoordinate()}a=this.get("tooltip");$("#mea",$(a.getElement())).text(b);a.setPosition(d)},a);f&&(a=$(b.getElement()),b=$("#title",a),b.length||(a.prepend("<span id='title'></span><br/>"),b=$("#title",a)),b.text(f))}var c=new ol.Sphere(6378137);app.MapDraw=function(d){this.tooltipOverlays=
[];this.features=new ol.Collection;this.source=new ol.source.Vector({features:this.features,wrapX:!0});this.vectorlayer=new ol.layer.Vector({source:this.source,style:function(b){return a(b,{color:"#ea803f",width:4,image:"images/arrow-y.png"})}});var c,f,e;this.mapPointerMoveHandler=function(a){if(!a.dragging){var b="Ctrl+\u5355\u51fb\u5f00\u59cb";if(c){var d=c.getGeometry();d instanceof ol.geom.Polygon?b="\u5355\u51fb\u7ee7\u7eed\uff0c\u53cc\u51fb\u7ed3\u675f\uff0cEsc\u53d6\u6d88":d instanceof ol.geom.LineString&&
(b="\u5355\u51fb\u7ee7\u7eed\uff0c\u53cc\u51fb\u7ed3\u675f\uff0cEsc\u53d6\u6d88")}f.innerHTML=b;e.setPosition(a.coordinate);f.classList.remove("hidden")}};this.mapViewportMouseout=function(){f.classList.add("hidden")};this.typeSelect=null;var l=this.vectorlayer,u=function(a){if(a=a.map.getFeaturesAtPixel(a.pixel,{layerFilter:function(a){return a===l},hitTolerance:10}))for(var b=0;b<a.length;++b)if(a[b].get("readonly"))return!1;return!0},k=new ol.interaction.Modify({features:this.features,condition:u,
insertVertexCondition:u});map.addInteraction(k);this.drawInteractionStartFun=function(d){k.setActive(!1);c=d.feature;b(c,m.newMeasureTooltip());c.setId(gen_uuid("rou"));c.setStyle(function(){return a(this,{color:"#1e7221",width:2,image:"images/arrow-y.png"})})};this.drawInteractionEndFun=function(a){var b=a.feature;if(b){a=b.get("tooltip");if(!a)return;var d=a.getElement();d.className="tooltip tooltip-static";d.innerHTML+='&nbsp;&nbsp;<a class="btn btn-info btn-xs">\u9009\u56fe</a>';var e=this;$("a",
$(d)).click(function(){e.getRouteCoverage(b,window.onRouteCoverage)});a.setOffset([0,-15]);b.setStyle(null)}c=null;k.setActive(!0)};this.drawInteractionCondition=function(a){return c||a.originalEvent.ctrlKey};var m=this;this.newMeasureTooltip=function(a){var b=document.createElement("div");b.className=a?"tooltip tooltip-static":"tooltip tooltip-measure";b.innerHTML='<span id="mea"></span>';a=new ol.Overlay({element:b,offset:[0,-18],positioning:"bottom-center"});map.addOverlay(a);m.tooltipOverlays.push(a);
return a};this.createTooltip=function(){f&&f.parentNode&&f.parentNode.removeChild(f);f=document.createElement("div");f.className="tooltip hidden";e=new ol.Overlay({element:f,offset:[15,0],positioning:"center-left"});map.addOverlay(e);m.tooltipOverlays.push(e)};var p=function(a){if(27==a.keyCode&&c){a=c.getGeometry();if(a instanceof ol.geom.Polygon){var b=a.getCoordinates()[0].length;var d=3}else a instanceof ol.geom.LineString&&(b=a.getCoordinates().length,d=2);b>d-1&&(m.drawInteraction.removeLastPoint(),
b===d&&(b=c.get("tooltip").getElement(),$(b).hide(),c.unset("tooltip"),m.drawInteraction.abortDrawing_?m.drawInteraction.abortDrawing_():(b=m.drawInteraction,b.o=null,b.j&&(b.j=null,b.C=null,b.B=null,b.oa.ia().clear(!0))),m.drawInteraction.dispatchEvent("drawend"),f.innerHTML="Ctrl+\u5355\u51fb\u5f00\u59cb"))}};this.bindEvent=function(){$("div").delegate(".tooltip-static","mouseenter",function(){$(f).hide()});$("div").delegate(".tooltip-static","mouseleave",function(){$(f).show()});$("#map").bind("keydown",
p)};this.unbindEvent=function(){$("div").undelegate(".tooltip-static","mouseenter");$("div").undelegate(".tooltip-static","mouseleave");$("#map").unbind("keydown",p)};this.map=null;d.map&&this.setMap(d.map)};app.MapDraw.prototype.clear=function(){this.source.clear();for(var a=0;a<this.tooltipOverlays.length;++a){var b=this.tooltipOverlays[a];this.map.removeOverlay(b);b=b.getElement();b.parentNode.removeChild(b)}this.tooltipOverlays=[]};app.MapDraw.prototype.linestring=function(a){this.clear();a?(this.setActive(!1),
this.typeSelect=null):"line"!==this.typeSelect&&(this.setActive(!1),this.typeSelect="line",this.setActive(!0))};app.MapDraw.prototype.polygon=function(a){this.clear();a?(this.setActive(!1),this.typeSelect=null):"area"!==this.typeSelect&&(this.setActive(!1),this.typeSelect="area",this.setActive(!0))};app.MapDraw.prototype.removeFeature=function(a){var b=this.vectorlayer.getSource(),d=this.map;if(null==a)$.each(b.getFeatures(),function(a,b){a=b.get("tooltip");d.removeOverlay(a);a=a.getElement();a.parentNode.removeChild(a)}),
b.clear();else if(a=b.getFeatureById(a)){var c=a.get("tooltip");d.removeOverlay(c);c=c.getElement();c.parentNode.removeChild(c);b.removeFeature(a)}};app.MapDraw.prototype.displayFeature=function(a,c,f,e){var d=this.source.getFeatureById(a);if(!d){this.active||this.linestring();var g=[];$.each(c,function(a,b){g.push(ol.proj.transform(b,"EPSG:4326","EPSG:3857"))});d=new ol.Feature({geometry:new ol.geom.LineString(g)});c=this.newMeasureTooltip(!0);var k=this,m="\u9009\u56fe",p=function(){k.getRouteCoverage(d,
window.onRouteCoverage)};e&&(e.buttonText&&(m=e.buttonText),e.buttonClick&&(p=e.buttonClick),e.readonly&&d.set("readonly",!0,!0));e=c.getElement();e.innerHTML=e.innerHTML+'&nbsp;&nbsp;<a class="btn btn-info btn-xs">'+m+"</a>";$("a",$(e)).click(p);b(d,c,f);d.getGeometry().changed();d.setId(a);this.source.addFeature(d)}map.getView().setCenter(ol.extent.getCenter(d.getGeometry().getExtent()))};app.MapDraw.prototype.isActive=function(){return this.active};app.MapDraw.prototype.setActive=function(a){if(a!==
this.active){var b=this.map;a?(b&&(b.on("pointermove",this.mapPointerMoveHandler),b.getViewport().addEventListener("mouseout",this.mapViewportMouseout),this.drawInteraction=new ol.interaction.Draw({source:this.source,type:"area"===this.typeSelect?"Polygon":"LineString",style:new ol.style.Style({fill:new ol.style.Fill({color:"rgba(255, 255, 255, 0.2)"}),stroke:new ol.style.Stroke({color:"rgba(0, 0, 0, 0.5)",lineDash:[10,10],width:2}),image:new ol.style.Circle({radius:5,stroke:new ol.style.Stroke({color:"rgba(0, 0, 0, 0.7)"}),
fill:new ol.style.Fill({color:"rgba(255, 255, 255, 0.2)"})})}),condition:this.drawInteractionCondition}),this.drawInteraction.on("drawstart",this.drawInteractionStartFun,this),this.drawInteraction.on("drawend",this.drawInteractionEndFun,this),this.bindEvent(),b.addInteraction(this.drawInteraction),b.addLayer(this.vectorlayer),this.createTooltip()),this.active=!0):(b&&(b.removeLayer(this.vectorlayer),b.removeInteraction(this.drawInteraction),this.unbindEvent(),b.getViewport().removeEventListener("mouseout",
this.mapViewportMouseout),b.un("pointermove",this.mapPointerMoveHandler),this.clear()),this.active=!1)}};app.MapDraw.prototype.setMap=function(a){this.map!==a&&(this.setActive(!1),this.clear(),this.map=a)};app.MapDraw.prototype.getRouteCoverage=function(a,b){var d="string"===typeof a?this.source.getFeatureById(a):a;a=new ol.format.WKT;var c=map.getLayer("AVCS").getProperties().getSelTypeNames;c&&(c=c(),myajax("../wfs?Request=routeCoverage",{typeNames:c.typeNames,subTypeNames:c.subTypeNames.join(","),
routepath:a.writeFeature(d)},function(a){if(a){var c=[],e=[],f=new ol.format.WKT,g=function(){var a=function(){var a=f.readFeature(this.geometry_wkt);a.setId(this.id);a.setProperties(this.properties);a.setProperties({type:this.type});e.push(a);return a},b=a.call(this),c=featureToTableElement(b),d=b.getProperties().subunits;if(d){var h=[],g=[];$.each(d,function(){var b=a.call(this);h.push(b);g.push(featureToTableElement(b))});b.setProperties({subunits:h});c.subunits=g}return c};$.each(a,function(a,
b){$.each(b.charts,function(){c.push(g.call(this))})});var l=map.getLayer("findENC").getSource();l.clear(!0);l.addFeatures(e);var r=map.getView().getProjection(),t=[];$.each(d.getGeometry().getCoordinates(),function(a,b){t.push(ol.proj.transform(b,r,"EPSG:4326"))});b({id:d.getId(),coords:t},{meta:a.AVCS.meta,charts:c})}}))};$(function(){map.on("click",function(a){if(a.originalEvent.altKey){var b=window.onChartClick;if(b){var c=[];map.forEachFeatureAtPixel(a.pixel,function(a,b){if(b.get("ENC")){var d=
featureToTableElement(a);c.some(function(a){return a.id===d.id})||c.push(d)}});0<c.length&&b({charts:c})}}})})})();app.MapLoadProgress=function(a){a=a||{};var b=a.target;"string"===typeof b&&(b=document.getElementById(b));this.element=b;this.error=this.loaded=this.loading=0;a.map&&this.setMap(a.map)};app.MapLoadProgress.prototype.addLoading=function(){0===this.loading&&this.show();++this.loading;this.update()};
app.MapLoadProgress.prototype.addLoaded=function(a){var b=this;setTimeout(function(){++b.loaded;a&&++b.error;b.update()},100)};app.MapLoadProgress.prototype.update=function(){var a=(this.loaded/this.loading*100).toFixed(1)+"%";this.element.style.width=a;if(this.loading===this.loaded){this.loaded=this.loading=0;var b=this;setTimeout(function(){b.hide()},500)}};app.MapLoadProgress.prototype.show=function(){this.element.style.visibility="visible";this.error=0;this.element.style.backgroundColor=""};
app.MapLoadProgress.prototype.hide=function(){this.loading===this.loaded&&(0===this.error?(this.element.style.visibility="hidden",this.element.style.width=0):this.element.style.backgroundColor="rgba(239, 27, 27, 0.6)")};app.MapLoadProgress.prototype.setMap=function(a){var b=this;a.getLayers().forEach(function(a){a.getSource().on("tileloadstart",function(){b.addLoading()});a.getSource().on("tileloadend",function(){b.addLoaded()});a.getSource().on("tileloaderror",function(a){b.addLoaded(!0);console.error(a)})})};
$(function(){new app.MapLoadProgress({target:document.getElementById("progress"),map:map})});app.control=app.control||{};app.control.OverviewMap=function(a){ol.control.OverviewMap.call(this,a);this.dragging=null;$(document.body).on("mousemove",this.onDrag.bind(this));$(document.body).on("mouseup",this.onEndDrag.bind(this));var b=this;this.getOverviewMap().on("click",function(a){b.getMap().getView().setCenter(a.coordinate)})};ol.inherits(app.control.OverviewMap,ol.control.OverviewMap);
ol.control.OverviewMap.prototype.onStartDrag=function(a){var b=$(a.target);this.dragging={el:b,evPos:{top:a.pageY,left:a.pageX},elPos:b.offset()}};ol.control.OverviewMap.prototype.onDrag=function(a){if(this.dragging){var b=this.dragging.el.offset();b={top:b.top+(a.pageY-this.dragging.evPos.top),left:b.left+(a.pageX-this.dragging.evPos.left)};this.dragging.evPos={top:a.pageY,left:a.pageX};this.dragging.el.offset(b)}};
ol.control.OverviewMap.prototype.onEndDrag=function(a){if(this.dragging){a=this.getMap();var b=this.dragging.el.position(),c=[this.dragging.el.width(),this.dragging.el.height()],d=a.getSize(),g=a.getView().getResolution(),f=b.left*Math.abs(d[0]/c[0]);c=b.top*Math.abs(d[1]/c[1]);b=[d[0]+f,0+c];d=a.getCoordinateFromPixel([0+f,d[1]+c]);f=a.getCoordinateFromPixel(b);d=[d[0],d[1],f[0],f[1]];a.getView().fit(d,a.getSize());a.getView().setResolution(g);this.dragging.el.offset(this.dragging.elPos);this.dragging=
null}};app.control=app.control||{};app.View=function(a){!a.extent||a.center&&ol.extent.containsCoordinate(a.extent,a.center)||(a.center=ol.extent.getCenter(a.extent));ol.View.call(this,a)};ol.inherits(app.View,ol.View);
(function(){function a(a){if(1===a.buttonstate){$(a.button).css("background-color","burlywood");var b=q[a.group];b&&$.each(b,function(){this!==a&&(this.buttonstate=0,$(this.button).css("background-color",""))})}else 0===a.buttonstate&&$(a.button).css("background-color","")}function b(b,c,d,n){var h=function(n){n=n||{};var e=document.createElement("button");$(e).attr("title",b);e.innerHTML=c;var h=this;h.button=e;n.group&&(h.buttonstate=0,h.group=n.group);q[n.group]||(q[n.group]=[]);q[n.group].push(h);
var f=function(){h.group&&(h.buttonstate=0===h.buttonstate?1:0,a(h));d.call(h)};e.addEventListener("click",f,!1);e.addEventListener("touchstart",f,!1);f=$(".maptoolbar")[0];f.appendChild(e);ol.control.Control.call(h,{element:f,target:n.target})};ol.inherits(h,ol.control.Control);n=new h(n);e.addControl(n);return n}function c(a,b,c){var d=function(a){var b={height:400,width:600,resizable:!0,scrollbars:"yes",title:null,dismove:!1,notitle:!1,closeOnEscape:!1,modal:!1};if(a)if("string"===typeof a){var d=
function(a){a=a.toUpperCase();return"Y"===a||"YES"===a||"T"===a||"TRUE"===a||"1"===a};$.each(a.split(/[,;]/),function(a,c){a=c.indexOf("=");if(-1!==a){var e=c.substring(0,a);c=c.substring(a+1);switch(e){case "dialogWidth":case "width":b.width=parseInt(c);break;case "dialogHeight":case "height":b.height=parseInt(c);break;case "scrollbars":b.scrollbars=c;break;case "resizable":b.resizable=d(c);break;case "title":b.title=c;break;case "dismove":b.dismove=d(c);break;case "notitle":b.notitle=d(c);break;
case "closeOnEscape":b.closeOnEscape=d(c);break;case "id":b.id=c;break;case "modal":b.modal=d(c)}}})}else"object"===typeof a&&(b=$.extend({},b,a));return b}(b),e;if(!d.modal&&d.id&&(e=t[d.id])){e.html($(a));return}e||(e=$('<div style="display:none;margin:16px 4px 0 4px;padding:0px;overflow:hidden"></div>'),!d.modal&&d.id&&(t[d.id]=e));e.html($(a));$("body").append(e);var f,v={"\u5173\u95ed":function(){f.dialog("close")}};c&&$.each(c,function(a,b){"function"===typeof b&&(v[a]=function(){b()&&f.dialog("close")})});
e.dialog({autoOpen:!0,resizable:d.resizable,height:"auto",width:d.width+4,modal:d.modal,closeOnEscape:d.closeOnEscape,closeText:null,open:function(){d.notitle?$(".ui-dialog-titlebar",$(this).parent()).hide():($(".ui-dialog-titlebar",$(this).parent()).show(),d.title&&$(this).dialog("option","title",d.title));$(this).dialog("option","position","center");f=$(this)},close:function(){$(this).dialog("destroy").remove();!d.modal&&d.id&&delete t[d.id]},buttons:v});e.dialog({draggable:!d.dismove})}var d=ol.proj.get("EPSG:3857"),
g=d.getExtent(),f=function(a){a=ol.extent.getWidth(g)/a;for(var b=[],d=[],c=2;24>c;++c)b[c]=a/Math.pow(2,c),d[c]="kk:"+c;return[b,d]}(256);d=new ol.source.WMTS({url:"../wmts",layer:"gmap",matrixSet:"EPSG:3857",format:"image/png",projection:d,tileGrid:new ol.tilegrid.WMTS({origin:ol.extent.getTopLeft(g),resolutions:f[0],matrixIds:f[1]}),style:"default",requestEncoding:"KVP"});f=new ol.layer.Tile({opacity:.7,source:d,name:"\u4e16\u754c\u5730\u56fe"});var e=new ol.Map({layers:[f],target:"map",controls:ol.control.defaults({attributionOptions:{collapsible:!1}}).extend([new app.control.OverviewMap({className:"ol-overviewmap ol-custom-overviewmap",
layers:[new ol.layer.Tile({source:d})],collapseLabel:"\u00bb",label:"\u00ab",collapsed:!1,interactive:!0,view:new ol.View})]),view:new app.View({zoom:6,minZoom:4,maxZoom:12,center:ol.proj.transform([120.059,17.246],"EPSG:4326","EPSG:3857"),extent:ol.proj.transformExtent([-360,85.0511287798066,360,-85.0511287798066],"EPSG:4326","EPSG:3857")}),logo:null});window.map=e;e.addControl(new ol.control.ScaleLine);e.addControl(new ol.control.ZoomSlider);var l=new ol.control.MousePosition({coordinateFormat:ol.coordinate.createStringXY(6),
projection:"EPSG:4326",undefinedHTML:"&nbsp;"});e.addControl(l);$(".ol-mouse-position").click(function(a){a.ctrlKey&&(1===l.proj?(l.proj=0,l.setProjection(ol.proj.get("EPSG:3857")),l.setCoordinateFormat(ol.coordinate.createStringXY(2))):(l.proj=1,l.setProjection(ol.proj.get("EPSG:4326")),l.setCoordinateFormat(ol.coordinate.createStringXY(6))))});var u=new ol.Overlay({element:document.getElementById("popupInfo")});e.addOverlay(u);e.on("pointermove",function(a){p.isActive()||(e.getTargetElement().style.cursor=
e.hasFeatureAtPixel(a.pixel,{layerFilter:function(a){return!a.get("ENC")}})?"pointer":"")});var k=$(".ol-zoomslider-thumb"),m=e.getView();k.attr("title","zoom="+m.getZoom());m.on("change:resolution",function(a){k.attr("title","zoom="+m.getZoom())});var p=new app.MapDraw({map:e});void 0===ol.Map.prototype.getLayer&&(ol.Map.prototype.getLayer=function(a){var b;this.getLayers().forEach(function(c){a==c.get("id")&&(b=c)});return b});window.resize=function(){$("#map").height(getWindowSize().h);e.updateSize()};
var q={};window.addToolbarButton=b;b("\u56fe\u5c42\u7ba1\u7406","<img src='images/layers.png'>",function(){function a(a,b){var c=a.get("name");if(c){var f='<li><div style="font:normal 15px heit;color:green;">'+c+'</div><div style="float:left;padding-left:40px;height:40px;display:inline-flex;"><label style="margin:auto;" for="'+b+'"><input id="'+b+'" class="visible" type="checkbox"/>&nbsp;\u663e\u793a</label></div><div style="display:inline-flex;height:40px;padding-left:20px;"><label style="margin:auto;padding-right:10px;">\u900f\u660e</label><input class="opacity" style="width:120px;" type="range" min="0" max="1" step="0.01"/></div>',
g=a.getProperties().typelist;g&&(f+='<br/><div style="padding-left:60px;">',$.each(g,function(a){var b=this.name;f+='<input id="id_'+a+'" name="typename" class="typename '+b+'" type="radio" '+(a===g.length-1?"checked":"")+' value="'+b+'">&nbsp;'+b+"<br/>";$.each(this.values,function(c){f+='&nbsp;&nbsp;&nbsp;&nbsp;<input id="id_'+(a+"_"+c)+'" name="subtypename" class="subtypename '+b+" "+this+'" type="checkbox" checked value="'+this+'">&nbsp;'+this+"<br/>"})}),f+="</div>");var h=$(f+"</li>");b=$("input.visible",
h);b.on("change",function(){a.setVisible(this.checked)});b.prop("checked",a.getVisible());b=$("input.opacity",h);b.on("input change",function(){a.setOpacity(parseFloat(this.value))});b.val(String(a.getOpacity()));var n=function(){var b=a.getProperties()||{};b.save_typename||(b.save_typename={},a.setProperties(b));var c=$(this);"radio"===c.attr("type")?b.save_typename[c.attr("name")]="#"+c.attr("id"):b.save_typename["#"+c.attr("id")]=c.prop("checked")};$("input.typename",h).on("input change",function(){n.call(this);
a.getSource().getProperties().loader()});$("input.subtypename",h).on("input change",function(){n.call(this);var b=$("input.typename:checked",h).val();$(this).hasClass(b)&&a.getSource().getProperties().loader(e.getView().calculateExtent(e.getSize()))});a.setProperties({getSelTypeNames:function(){var a=$("input.typename:checked",h).val(),b=[];$("input.subtypename."+a+":checked",h).each(function(a){b[a]=$(this).val()});return{typeNames:a,subTypeNames:b}}});$.each(a.getProperties().save_typename||{},
function(a,b){"boolean"===typeof b?$(a,h).prop("checked",b):$(b,h).prop("checked",!0)});d.append(h)}}var b=$("<div></div"),d=$("<ul></ul>").appendTo(b);e.getLayers().forEach(function(b,c){a(b,"l"+c);b instanceof ol.layer.Group&&b.getLayers().forEach(function(b,d){a(b,"l"+c+"_"+d)})});c(b,{title:"\u56fe\u5c42\u7ba1\u7406",resizable:!1,width:408,id:"layermgr"})});var r=b("\u5236\u5b9a\u822a\u7ebf","R",function(){$(u.getElement()).popover("destroy");p.linestring(0===this.buttonstate);e.getLayer("findENC").getSource().clear(!0)},
{group:"M"}),t={};window.showDialog=c;window.highlightChart=function(a,b){a=(a=e.getLayer("findENC").getSource().getFeatureById(a))?a:void 0;a&&(a.set("highlight",b),b&&e.getView().setCenter(ol.extent.getCenter(a.getGeometry().getExtent())))};window.displayRoute=function(b,c,d,e){p.displayFeature(b,c,d,e);r.buttonstate=1;a(r)};window.removeRoute=function(a){p.removeFeature(a)};window.displayShip=function(a,b,c){var d=e.getLayer("_ship_");if(!d){d=new ol.layer.Vector({id:"_ship_",source:new ol.source.Vector,
style:function(a){return[new ol.style.Style({image:new ol.style.Icon({anchor:[.5,52],anchorXUnits:"fraction",anchorYUnits:"pixels",src:"images/place-ship.png"}),text:new ol.style.Text({text:a.get("title"),fill:null,stroke:new ol.style.Stroke({color:"white",width:1}),offsetY:18,font:"normal normal 14px SimSun"})})]}});new ol.interaction.Select;var f=new ol.interaction.Select({condition:ol.events.condition.click,layers:[d],style:d.getStyle()});f.on("select",function(a){if("function"===typeof window.onSelectShip&&
(a=this.getFeatures(),a.getLength())){var b=a.item(0);a.clear();window.onSelectShip(b.getId())}},f);e.addLayer(d);e.addInteraction(f)}f=d.getSource().getFeatureById(a);var g=[];$.each(b,function(a,b){g.push(ol.proj.transform(b,"EPSG:4326","EPSG:3857"))});f||(f=new ol.Feature,f.setId(a));f.set("title",c);f.setGeometry(new ol.geom.Point(g));d.getSource().addFeature(f);e.getView().setCenter(ol.extent.getCenter(f.getGeometry().getExtent()))};window.removeShip=function(a){var b=e.getLayer("_ship_");b&&
(null==a?b.getSource().clear():(a=b.getSource().getFeatureById(a))&&b.getSource().removeFeature(a))};window.getRouteCoverage=function(a,b){p.getRouteCoverage(a,b)};window.findAllChart=function(a,b){var c=e.getLayer("findENC").getSource();c.clear(!0);a&&myajax("../wfs?Request=find",{cond:j2s(a)},function(a){if(a){var d=[],e=[],f=new ol.format.WKT;$.each(a.charts,function(){var a=f.readFeature(this.geometry_wkt);a.setId(this.id);a.setProperties(this.properties);a.setProperties({type:this.type});d.push(a);
e.push(featureToTableElement(a))});c.addFeatures(d);b({meta:a.meta,charts:e})}})};window.findChartsByRoute=function(a,b){var c=e.getLayer("findENC").getSource();c.clear(!0);for(var d=[],f,g=0;g<a.length;g++)f=a[g],d.push(f[0]+" "+f[1]);myajax("../wfs?Request=routeCoverage",{routepath:"LINESTRING("+d.join(",")+")",ll:1},function(a){if(a){var d=[],e=[],f=new ol.format.WKT;$.each(a.AVCS.charts,function(a,b){a=f.readFeature(b.geometry_wkt);a.setId(b.id);a.setProperties(b.properties);a.setProperties({type:b.type});
d.push(a);e.push(featureToTableElement(a))});c.addFeatures(d);b({meta:a.AVCS.meta,charts:e})}})}})();
